--OPTION1 WITHOUT MERGE-
SELECT FUNCTION_NAME, COUNT(FUNCTION_NAME) AS FUNCION_COUNT
FROM [dbo].[data_for_merge]
UNPIVOT(
          FUNCTION_NAME for PERSON_NAME in 
		  ( [Alex] ,[Carlos] ,[Charles] ,[Daniel] ,[Esteban] ,[Fred] ,[George] ,[Lando] ,[Lewis] )
        ) AS test_unpivot
GROUP BY FUNCTION_NAME
--OPTION 2  WITH MERGE

CREATE TABLE TEMP
(
FUNCTION_NAME  NVARCHAR(50),
FUNCTION_COUNT INT
)

CREATE PROCEDURE MERG_T
@NAME  VARCHAR(25)
AS
BEGIN
declare @mys nvarchar(1000)
SET @mys='MERGE TEMP TARGET
USING (SELECT '+ @NAME +' AS NAME  FROM [dbo].[data_for_merge] ) SOURCE on TARGET.FUNCTION_NAME=SOURCE.NAME
WHEN MATCHED  THEN  UPDATE SET FUNCTION_COUNT=FUNCTION_COUNT+1
WHEN NOT MATCHED  AND SOURCE.NAME IS NOT NULL THEN INSERT (FUNCTION_NAME,FUNCTION_COUNT)
					VALUES (SOURCE.NAME,1);'
EXEC SP_EXECUTESQL @mys
END

EXEC MERG_T @Name= Alex
EXEC MERG_T @Name= Carlos
EXEC MERG_T @Name= Charles
EXEC MERG_T @Name= Daniel
EXEC MERG_T @Name= Esteban
EXEC MERG_T @Name= Fred
EXEC MERG_T @Name= George
EXEC MERG_T @Name= Lando
EXEC MERG_T @Name= Lewis

SELECT * FROM TEMP
