--TASK 1
SELECT  M.FIRST_NAME, M.LAST_NAME
FROM (SELECT MANAGER_ID, COUNT(EMPLOYEES_ID) AS CNT
	  FROM EMPLOYEES 
	  GROUP BY MANAGER_ID) T JOIN EMPLOYEES M ON  T.MANAGER_ID=M.EMPLOYEES_ID
WHERE CNT>6

--TASK 2
SELECT D.DEPARTMENT_NAME, S.MIN_SAL, S.MAX_SAL
FROM (SELECT DEPARTMENT_ID, MIN(SALARY-SALARY*COMMISSION_PCT/100) AS MIN_SAL,MAX(SALARY-SALARY*COMMISSIONPCT/100) AS MAX_SAL
	  FROM EMPLOYEES 
	  GROUP BY DEPARTMENT_ID)S JOIN DEPARTMENTS D ON S.DEPARTMENT_ID=D.DEPARTMENT_ID

--TASK 3
SELECT TOP 1 REGION_NAME 
FROM (SELECT C.REGION_ID AS R_ID,COUNT(EMPLOYEES) AS CNT
		FROM EMPLOYEEES  E JOIN  DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
						   JOIN LOCATIONS L    ON D.LOCATION_ID=L.LOCATION_ID 
						   JOIN COUNTRIES C    ON L.COUNTRY_ID=C.COUNTRY_ID
		GROUP BY C.REGION_ID) T JOIN REGIONS R ON T.R_ID=R.REGION_ID
ORDER BY T.CNT

--TASK 4
SELECT DISTINCT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, ROUND(AVG(E.SALARY) OVER(PARTITION BY E.DEPARTMENT_ID)/AVG(E.SALARY) OVER()*100,2) AS  PRC
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 

--TASK 5
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME, E.LAST_NAME,T.DEPYEAR
FROM (SELECT EMPLOYEE_ID,DEPARTMENT_ID,SUM(CASE WHEN END_DATE IS NULL THEN DATEDIFF(YEAR,START_DATE,GETDATE()) 
											            ELSE DATEDIFF(YEAR,START_DATE,END_DATE) END) AS DEPYEAR	
	  FROM JOB_HISTORY
	  GROUP BY EMPLOYEE_ID,DEPARTMENT_ID) T JOIN EMPLOYEES E ON T.EMPLOYEE_ID=E.EMPLOYEE_ID JOIN DEPARMENTS D ON T.DEPARTMENT_ID=D.DEPARTMENT_ID 
WHERE JOBYEAR>10

--TASK 6
SELECT * 
FROM (SELECT  FIRST_NAME,LAST_NAME,SALARY, RANK() OVER(ORDER BY SALARY DESK) AS RNKSAL
	  FROM EMPLOYEES) T
WHERE RNKSAL BETWEEN 5 AND 10

