/*
Create database temp and do 'import flat file' 3 generate files from https://mockaroo.com/
AdDATA.csv,ClDATA.csv,MDATA.csv
*/

INSERT INTO TravelAgency.dbo.DimManagers
(FirstName,LastName, Passport,Position,PhoneNumber,Territory,Email)
SELECT TOP 1000 FIRST_NAME,LAST_NAME, SUBSTRING(REPLACE(CONVERT(NVARCHAR(50),NEWID()),'-',''),1,20),
JOB,'+'+CONVERT(NVARCHAR,FLOOR(RAND(CHECKSUM(NEWID()))*1000000))+ CONVERT(NVARCHAR,FLOOR(RAND(CHECKSUM(NEWID()))*1000000)),
TERRITORY,CONCAT(SUBSTRING(CONCAT(LAST_NAME,'_',FIRST_NAME),1,15),'@gmail.com')
FROM TEMP.DBO.MDATA


INSERT INTO TravelAgency.dbo.DimClients
(FirstName,LastName,TypeClient, Passport,PhoneNumber,Adress,BirthDate)
SELECT TOP 100000 C1.FIRST_NAME,C2.LAST_NAME,
CASE WHEN RAND(CHECKSUM(NEWID()))<0.5 THEN 'GOLD' WHEN RAND(CHECKSUM(NEWID()))>0.5  THEN 'SILVER'  ELSE 'CLASSIC' END, 
SUBSTRING(REPLACE(CONVERT(NVARCHAR(50),NEWID()),'-',''),1,20),
'+'+CONVERT(NVARCHAR,FLOOR(RAND(CHECKSUM(NEWID()))*1000000))+ CONVERT(NVARCHAR,FLOOR(RAND(CHECKSUM(NEWID()))*1000000)),
Iif(RAND(CHECKSUM(NEWID()))>0.5,C1.Adress,c2.Adress),
DATEADD(DAY, FLOOR(RAND(CHECKSUM(NEWID()))*20000), '1945-01-01')
FROM TEMP.DBO.ClData C1 CROSS JOIN TEMP.DBO.ClData C2 


INSERT INTO TravelAgency.dbo.DimAirFlight
( Departure,CityDeparture, Arrival, CityArival, Baggage, FlightNumber)
SELECT TOP 1000 A1.D1,A1.DCITY,DATEADD(MINUTE, FLOOR(RAND(CHECKSUM(NEWID()))*2160) , A1.D1),A2.CITY,
CONVERT(NVARCHAR(10),FLOOR(RAND(CHECKSUM(NEWID()))*25)) AS BAG,
CONCAT(SUBSTRING(A1.DCITY,1,1),SUBSTRING(A2.CITY,1,1),CONVERT(NVARCHAR,FLOOR(RAND(CHECKSUM(NEWID()))*100000))) AS FL
FROM (SELECT DATEADD(MINUTE, FLOOR(RAND(CHECKSUM(NEWID()))*3679200) , '2015-01-01 08:22') AS D1,
City AS DCITY  FROM TEMP.DBO.ADData ) A1 CROSS JOIN TEMP.DBO.ADData A2
WHERE A1.DCITY!=A2.City AND LEN(A1.DCITY)<=25 AND LEN(A2.CITY)<=25
ORDER BY FLOOR(RAND(CHECKSUM(NEWID()))*1000) 



INSERT INTO TravelAgency.dbo.DimHotels
(HotelName, HotelType, Country, City, Adress, LocationType,	RoomType,	FoodType,Price)
SELECT TOP 1000 A.Name, 
 CASE WHEN RAND(CHECKSUM(NEWID()))<0.2 THEN 'APARTHOTEL'
     WHEN RAND(CHECKSUM(NEWID()))<0.3  THEN 'SEA HOTEL' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.5  THEN '2 STAR' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.7  THEN '3 STAR' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.8  THEN '4 STAR' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.9  THEN '5 STAR' 
ELSE 'HOSTEL' END,  
A.Country,SUBSTRING(A.City,1,25),A.Adress,
CASE WHEN RAND(CHECKSUM(NEWID()))<0.3 THEN 'DBL'
     WHEN RAND(CHECKSUM(NEWID()))<0.3  THEN 'SGL' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.6  THEN 'TRPL' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.8  THEN 'TWINSOLO' 
ELSE 'QUAD' END, 
CASE WHEN RAND(CHECKSUM(NEWID()))<0.2 THEN 'STANDART'
     WHEN RAND(CHECKSUM(NEWID()))<0.4  THEN 'DELUXE' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.5  THEN 'APPARTMENT' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.6  THEN 'SEA VIEW' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.7  THEN 'DELUXE' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.8  THEN 'SUIT' 
ELSE 'STUDIO' END, 
CASE WHEN RAND(CHECKSUM(NEWID()))<0.2 THEN 'AI'
     WHEN RAND(CHECKSUM(NEWID()))<0.4  THEN 'UAI' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.5  THEN 'HB' 
	 WHEN RAND(CHECKSUM(NEWID()))<0.6  THEN 'FB' 
	 WHEN RAND(CHECKSUM(NEWID()))>0.7  THEN 'BB'
ELSE 'RO' END,
ROUND(RAND(CHECKSUM(NEWID()))*10000,2)
FROM TEMP.DBO.ADData A 


INSERT INTO TravelAgency.dbo.FctSales
( ClientId, ManagerId, HotelId, AviaId , SalesDate,   StartDate,   EndDate	,   Discount,   Price)
SELECT TOP 1000000 T1.CLID,T1.MID,T1.HID,T1.AVIAID, DATEADD(DAY, -1*FLOOR(RAND(CHECKSUM(NEWID()))*365),D1),
        DATEADD(DAY,-1*FLOOR(RAND(CHECKSUM(NEWID()))*3),D1),DATEADD(DAY, FLOOR(RAND(CHECKSUM(NEWID()))*30),D1),
		T1.DISC,T1.PR
FROM (SELECT  FLOOR(RAND(CHECKSUM(NEWID()))*100000) AS CLID,
			FLOOR(RAND(CHECKSUM(NEWID()))*1000) AS MID,
			FLOOR(RAND(CHECKSUM(NEWID()))*1000) AS HID,
			AviaId AS AVIAID, 
			FLOOR(RAND(CHECKSUM(NEWID()))*20) aS DISC,
			ROUND(RAND(CHECKSUM(NEWID()))*10000,2) AS PR,
			DEPARTURE AS D1
			FROM TravelAgency.dbo.DimAirFlight CROSS JOIN TravelAgency.dbo.DimClients) T1 
WHERE MID>0 and HID>0 and CLID>0

